Repository DevBas-ed/Guess-the-number, pull requests merged in 2022-10, with the labels that each got.

#1 Added initializers to the random number generator
  script.js
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#3 Added function to change background color.
  script.js
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#4 Updated Script.js
  script.js
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#5 Updated Script.js
  script.js
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#8 Create README.md
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#11 Changed background color of lower guess to an orange color, which sig…
  script.js
Labels: Hacktoberfest, hacktoberfest-accepted
